site_name: edgartools
theme:
  name: "readthedocs"

nav:
  - Overview: index.md
  - Filtering: filtering-filings.md
  - Filings: working-with-filings.md
  - Companies: company.md
  - Attachments: attachments.md
  - Insider Filings: insider-filings.md
  - XBRL and Financials:
    - Getting XBRL from Filings: getting-xbrl.md
    - Querying XBRL Facts: xbrl-querying.md
  - SGML: sgml.md
  - Data Objects: data-objects.md
  - Local Storage: local-data.md
  - Quick Guide: quick-guide.md
  - User Journeys: examples.md
